name: isolate_helper
description: "A library to help with isolate communication."
version: 1.0.0
homepage: https://github.com/NexPlugs/isolate_helper
repository: https://github.com/NexPlugs/isolate_helper

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  dart_ui_isolate: ^1.1.1
  flutter:
    sdk: flutter
  nanoid: ^1.0.0
  plugin_platform_interface: ^2.0.2
  synchronized: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
 
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass


topics:
  - isolate
  - thread

